name: github variables
on: push
jobs:
  print:
   runs-on: ubuntu-latest
   steps:
    - name: Run github action variable
      run: echo "Print the run number $GITHUB_RUN_NUMBER "
    - name: Print the Image name
      run: echo "My image name is myiamge01:$GITHUB_RUN_NUMBER "
   
