name: Install multiple versions of nodejs on multiple runners
on: workflow_dispatch
jobs:
 install-node:
   continue-on-error: true
   strategy:
     matrix:
      node-version: [27,16,18,24]
      operating-system: [ubuntu-latest, windows-latest]
      exclude:
        - node-version: 27
          operating-system: ubuntu-latest
        - node-version: 27
          operating-system: windows-latest
      include:
        - node-version: 12
          operating-system: macos-latest
   runs-on: ${{ matrix.operating-system }}
   steps:
    - name: Install nodejs
      uses: actions/setup-node@v7
      with:
       node-version: ${{ matrix.node-version }}
