name: Install nodejs and python3
on: push
jobs:
  install-python:
   runs-on: ubuntu-latest
   steps:
    - name: Install python 
      uses: actions/setup-python@v7
      with:
       python-version: ${{ secrets.PYTHONVERSION }}
